# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: ZinerX/kernel_build_action_op9r_gcc_test@main
        with:
          kernel-url: https://github.com/DawfukFR/kernel_oneplus_sm8250
          kernel-branch: OOS13.1
          config: vendor/lito-perf_defconfig
          arch: arm64
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r487747c
          disable-lto: true
          anykernel3: false
          aosp-gcc: true
          extra-cmd: LLVM_IAS=1 LLVM=-14
