# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: ZinerX/kernel_build_action_op9r_gcc_test@main
        with:
          kernel-url: https://github.com/ZinerX/android_kernel_oneplus_sm8250
          kernel-dir: msm-4.19
          kernel-branch: oneplus/sm8250_u_14.0.0_op9r
          config: lito_perf_defconfig
          arch: arm64
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          android-version: 14
          aosp-clang-version: r487747c
          disable-lto: true
          anykernel3: false
          vendor: true
          vendor-url: https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8250
          vendor-dir: vendor
          vendor-branch: oneplus/sm8250_u_14.0.0_op9r
          aosp-gcc: true
